version: '3.5'

services:
  dFront_service:
    container_name: dfront-container
    image: nginx:1.20.1
    restart: always
    volumes:
      - /home/donbungle/Proyectos/devices/dFront/:/usr/share/nginx/html
    ports:
        - "9111:80"

  app:
    container_name: base_app
    restart: always
    build:
      context: ./
    command: sh -c "cd projapi && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    links:
      - postgres
    environment:
      POSTGRES_PASSWORD: '1q2w3e4r5t'
      POSTGRES_USER: 'postgres'
      POSTGRES_URL: postgres
      POSTGRES_DB: 'base_db'
    networks:
      - postgres
    depends_on:
      - postgres

  postgres:
    container_name: base_db
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: 'base_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1q2w3e4r5t'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "8001:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: base_db_admin
    image: dpage/pgadmin4:6.6
    environment:
      PGADMIN_DEFAULT_EMAIL: 'victor.catalan@device.cl'
      PGADMIN_DEFAULT_PASSWORD: '123456'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8002:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
    postgres:
      driver: bridge

volumes:
    postgres:
    pgadmin:
